### ISSUE TITLE
Posts for older publications

### ISSUE THREAD

**Issue by josephholler** [HEGSRR/HEGSRR.github.io#1]
@Peter-Kedron and @SarahBardin : We needed posts for older publications on the blogroll. I just quickly added some for Dimaggio and the laws paper: https://github.com/HEGSRR/HEGSRR.github.io/commit/41f74fb075597d18a3f93f60e18c3ed773a81a93 

- [x] is DiMaggio post ok? https://github.com/HEGSRR/HEGSRR.github.io/blob/master/_posts/2022-06-01-replication-dimaggio.md
- [x] is Laws post ok? https://github.com/HEGSRR/HEGSRR.github.io/blob/master/_posts/2022-02-17-replication-laws.md 
- [x] Need a post for the R&R in remote sensing paper. 
- [x] I need to post the metadata conference paper
- [x] UCGIS 2022 workshop
- [x] UCGIS 2023 presentation 
- [x] missing other presentations?

**Comment by SarahBardin** [comment]
I'm fine with the DiMaggio post. I'll quibble slightly with whether it's too extreme to claim this is the "first formal replication study in the geographical sciences." Marynia Kolak and Luc Anselin replicated a well-known policy study (https://journals.sagepub.com/doi/full/10.1177/0160017619869781) and then used a variety of spatial regression models to elucidate potential differences in associations depending on the assumed spatial processes that may be at play.

**Comment by josephholler** [comment]
Ok, I toned it down to "one of the first".  Just glancing at the Kolak and Anselin publication, does it have a compendium / data / code ? I suspect ours is more complete in terms of components of an open science replication.

**Comment by SarahBardin** [comment]
I don't believe the article that I pointed you to does, but this was a spinoff from her dissertation and there she points to a (broken) link on her personal GitHub. I believe it should point here though: https://github.com/Makosak/SpatialDataScience-Notebooks/blob/master/MLDA%20Experiment%2C%20Panel%20Data%20Setup.ipynb

So, at least the code is available. The data are public data, but she doesn't point to where she obtained them from in the code. 

Ours is definitely more complete.

**Comment by Peter-Kedron** [comment]
I agree that 'early' or 'one of few' is better. Remember that was that Davies article we cited from ~50 years ago that is in the same spirit. Also a bunch of our survey respondents were saying they do these things. Whether we agree or not, they might be upset. Thanks for the careful read everyone.
